# Generated by Django 2.2.17 on 2025-04-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asctime', models.CharField(blank=True, max_length=250, null=True, verbose_name='日志时间')),
                ('pathname', models.CharField(blank=True, max_length=250, null=True, verbose_name='文件路径')),
                ('filename',
                 models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='文件名称')),
                ('funcName',
                 models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='函数名')),
                ('line_no', models.IntegerField(blank=True, default=0, null=True, verbose_name='行号')),
                ('levelname',
                 models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='日志级别')),
                ('message', models.TextField(blank=True, null=True, verbose_name='日志内容')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统日志信息表',
                'verbose_name_plural': '系统日志信息表',
            },
        ),
    ]
